Lots of development: no args benchmark input | new export + compile options (#18)
* README typo fix

* We allow users to set up their own logging easily, we make the behncmark_model API take a config instead of args so that the API is independent of the argparser, and we update READMEs

* Added checks on config

* Formatting

* setup logging before argparsing to capture the logs in argparse. Fix the benchmark runner to have an up-to-date API. Remove regex based parsing of arguments-to-dict.

* bug fixes

* formatting

* remove args to dict

* README update

* Bug fixes

* Added new export-compile options, removed the passing around of the logger

* type hinting

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -34,8 +34,8 @@ jobs:
         cd examples/mnist
         mkdir -p ../results
         for i in {0..14}; do
-          echo "Running benchmark with conversion $i"
-          timeout 60s python benchmark.py --model-path=./model/mnist.pt --data-dir=data_for_inference --conversion $i > ../results/benchmark_conversion_$i.txt 2>&1 || echo "Conversion $i failed due to timeout or error" > ../results/benchmark_conversion_$i.txt
+          echo "Running benchmark with data loader, with conversion $i"
+          timeout 60s python benchmark_with_dataloader.py --model-path ./model/mnist.pt --data-dir data/data_for_inference --conversions $i > ../results/benchmark_conversion_$i.txt 2>&1 || echo "Conversion $i failed due to timeout or error" > ../results/benchmark_conversion_$i.txt
         done
 
     - name: Upload benchmark results
